language: node_js
node_js:
  - "node"


services:
  - mysql

before_install:
  - mysql -u root --password="" < ./test/integration/travis.sql

install:
  - npm install

script:
  - npm run cover
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"

# Coveralls token
service_name: travis-pro
repo_token: aArWPfKKBc1t2E88NFSv5ITIiuTkt7V1w

# whitelist
branches:
  only:
    - master
    - stable
    - develop
    - /^deploy-.*$/

