language: node_js
node_js:
  - "node"


services:
  - mysql

before_install:
  - mysql -u root --password=""
  - CREATE DATABASE IF NOT EXISTS `quizzes_platform_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
  - USE `quizzes_platform_test`;

install:
  - npm instal

script:
  - npm run cover

script:
  - npm test

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

# Coveralls token
service_name: travis-pro
repo_token: aArWPfKKBc1t2E88NFSv5ITIiuTkt7V1w

# whitelist
branches:
  only:
    - master
    - stable
    - travis
    - /^deploy-.*$/

